---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/auth/sign_in":
    post:
      summary: Logs in the user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: User logged in successfully
        '401':
          description: Invalid login credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
